### ISSUE TITLE
OVERCHARGED for FREESentinel BLE

### ISSUE THREAD

**Issue by CryptonightCanada** [XYOracleNetwork/xyo-foundation#64]
My Visa was charged many occasions for the free (pay shipping only) Sentinel_ble
Jun 12, 2020 	Visa Debit purchase - 3191 XYGEONEW	-$93.87 		
Jun 12, 2020 	Visa Debit purchase - 2955 XYGEONEW        -$25.15
Jun 15, 2020 	Visa Debit purchase - 4285 XYGEONEW	-$49.04 

Jun 17, 2020 	Visa Debit purchase - 3191 XYGEONEW	-$94.01
Jun 17, 2020 	Visa Debit purchase - 2955 XYGEONEW	-$25.18 
Jun 19, 2020 	Visa Debit purchase - 4285 XYGEONEW	-$48.71

Jul 20, 2020 	Visa Debit purchase - 2844 XYGEO8662005685	-$48.69 	

Jul 23, 2020 	
Visa Debit debit adjustment - 0000 XYGEO8662005685	-$48.50 

Please return my funds to my Royal Bank of Canada account.
I could have used one of three email addresses (xyo@tunercar.ca, ryan@tunercar.ca, cryptonightcanada@gmail.com)

**Comment by Dtat199188** [comment]
Doesn't even look real.

**Comment by MartyrMusic** [comment]
> Doesn't even look real.

Agreed 100%☝️

**Comment by Seyvick** [comment]
Eso no es real
